version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dotnet-patches:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.Extensions.*"
        update-types:
          - "patch"
      opentelemetry:
        patterns:
          - "OpenTelemetry*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "Microsoft.OpenApi"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
