extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  otlphttp/incidentcompass:
    endpoint: http://api:8080/
    compression: none

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/incidentcompass]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/incidentcompass]