@IncidentCompass.Api_HostAddress = http://localhost:5198

GET {{IncidentCompass.Api_HostAddress}}/api/v1/health
Accept: application/json

###

GET {{IncidentCompass.Api_HostAddress}}/api/v1/users/me
Accept: application/json
X-Demo-User-Id: alice
X-Demo-Tenant-Id: local
X-Demo-Roles: developer,admin
X-Demo-Groups: demo,engineering

###
